import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const Nova = localfont({
  src: [{
      path: "../public/fonts/Fontspring-DEMO-proximanova-black.otf",
      weight: "400"
    }],
  variable: "--font-nova",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Nova.variable} ${Nova.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
