import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const proximaNova = localFont({
  src: "../public/fonts/Fontspring-DEMO-proximanova-regular.otf",
  variable: "--font-proxima-nova",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${proximaNova.className} ${proximaNova.variable} ${proximaNova.variable}`}>
      <body className={proximaNova.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}